ALTER TYPE "LeadStatus" ADD VALUE 'NEEDS_REVIEW';
ALTER TYPE "LeadStatus" ADD VALUE 'REVIEW_PRESENTED';
ALTER TABLE "ClientBatch" ADD COLUMN "review" JSONB NOT NULL DEFAULT '[]';
ALTER TABLE "ClientBatch" ADD COLUMN "revision" INTEGER NOT NULL DEFAULT 0;
